### ISSUE TITLE
BUG: I don't have 12 cores :-(

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/seq2science#391]
**Describe the bug**

```
 seq2science run atac_seq --cores 4
Traceback (most recent call last):
  File "/home/simon/anaconda3/envs/seq2science/bin/seq2science", line 283, in <module>
    main()
  File "/home/simon/anaconda3/envs/seq2science/bin/seq2science", line 47, in main
    _run(args, base_dir, workflows_dir, config_path)
  File "/home/simon/anaconda3/envs/seq2science/bin/seq2science", line 213, in _run
    raise ValueError("Please specify at least 12 cores.")
ValueError: Please specify at least 12 cores.
```

**To Reproduce**

```
seq2science run atac_seq --cores 4
```
**Expected behavior**

Run with less cores, but slower.

**Comment by Maarten-vd-Sande** [comment]
This is an "issue" with how snakemake is incapable of scaling pipes to lower threads (alignment 10 threads + 2 threads sorting). I can see how this is unexpected behaviour, and the solution should be easy.
