### ISSUE TITLE
BUG: profile parsing goes wrong

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#508]
**Describe the bug**
```
seq2science run download-fastq -j 150 --keep-going  --profile ocimum --dryrun
Traceback (most recent call last):
  File "/home/sande/anaconda3/envs/seq2science/bin/seq2science", line 8, in <module>
    main()
  File "/home/sande/anaconda3/envs/seq2science/lib/python3.7/site-packages/seq2science/cli.py", line 46, in main
    _run(args, base_dir, workflows_dir, config_path)
  File "/home/sande/anaconda3/envs/seq2science/lib/python3.7/site-packages/seq2science/cli.py", line 263, in _run
    add_profile_args(profile_file, parsed_args)
  File "/home/sande/anaconda3/envs/seq2science/lib/python3.7/site-packages/seq2science/cli.py", line 224, in add_profile_args
    for k2, v2 in profile[k].items():
AttributeError: 'list' object has no attribute 'items'
```

```
# execution
cores: 48
resources:
  - parallel_downloads=3
  - mem_gb=64
config:
  - email=M.vanderSande@science.ru.nl
  - ascp_path=$HOME/.aspera/connect/bin/ascp
  - ascp_key=$HOME/.aspera/connect/etc/asperaweb_id_dsa.openssh
keep-going: True


# environment
use-conda: True
use-singularity: False
```

**To Reproduce**
Please include your **config.yaml**, your **samples.tsv**, and the complete/relevant **output**.

**Expected behavior**

**Screenshots**

**Comment by siebrenf** [comment]
s2s uses dicts for all these fields. these old profiles supply lists. 

I could make a parser that changes lists with `=` to dicts. But really the snakemake-profiles need to be fixed. Especially since we need to supply API flags now, rather than CLI flags.

In fact, I should have done this already :p #462
