### ISSUE TITLE
BUG: [chip-seq: error combine_peaks]

### ISSUE THREAD

**Issue by dzijlmans** [vanheeringen-lab/seq2science#625]
**Describe the bug**

Pipeline worked wonderfully up until the combining of called peaks

```
Error in rule combine_peaks:
    jobid: 94
    output: /scratch/dzijlmans/DZ034/results/macs2/GRCm39_combinedsummits.bed
    log: /scratch/dzijlmans/DZ034/results/log/combine_peaks/GRCm39-macs2.log (check log file(s) for error message)
    conda-env: /vol/mbconda/dzijlmans/envs/seq2science/lib/python3.8/site-packages/seq2science/.snakemake/eb131cbd
    shell:

        combine_peaks -i /scratch/dzijlmans/DZ034/results/macs2/GRCm39-DZ-EmT-cl2-H2K27me3-1-Z16_S8_summits.bed /scratch/dzijlmans/DZ034/results/macs2/GRCm39-DZ-EmT-cl2-H2K27me3-2-Z17_S16_summits.bed /scratch/dzijlmans/DZ034/results/macs2/GRCm39-DZ-EmT-cl2-HA-1-Z14_S6_summits.bed /scratch/dzijlmans/DZ034/results/macs2/GRCm39-DZ-EmT-cl2-HA-2-Z15_S7_summits.bed /scratch/dzijlmans/DZ034/results/macs2/GRCm39-DZ-EmT-cl2-input-Z18_S11_summits.bed /scratch/dzijlmans/DZ034/results/macs2/GRCm39-DZ-R1WT-Ezh2-1-Z01_S1_summits.bed /scratch/dzijlmans/DZ034/results/macs2/GRCm39-DZ-R1WT-Ezh2-2-Z03_S2_summits.bed /scratch/dzijlmans/DZ034/results/macs2/GRCm39-DZ-R1WT-H2K27me3-2-Z05_S12_summits.bed /scratch/dzijlmans/DZ034/results/macs2/GRCm39-DZ-R1WT-HA-1-Z06_S3_summits.bed /scratch/dzijlmans/DZ034/results/macs2/GRCm39-DZ-R1WT-HA-2-Z07_S13_summits.bed /scratch/dzijlmans/DZ034/results/macs2/GRCm39-DZ-R1WT-Input-Z13_S10_summits.bed /scratch/dzijlmans/DZ034/results/macs2/GRCm39-DZ-R1WT-Sall1-1-Z08_S4_summits.bed /scratch/dzijlmans/DZ034/results/macs2/GRCm39-DZ-R1WT-Sall1-2-Z09_S14_summits.bed /scratch/dzijlmans/DZ034/results/macs2/GRCm39-DZ-R1WT-Sall4-1-Z11_S15_summits.bed /scratch/dzijlmans/DZ034/results/macs2/GRCm39-DZ-R1WT-Sall4-2-Z12_S5_summits.bed -g /scratch/dzijlmans/DZ034/genomes/GRCm39/GRCm39.fa.sizes         --window 200 > /scratch/dzijlmans/DZ034/results/macs2/GRCm39_combinedsummits.bed 2> /scratch/dzijlmans/DZ034/results/log/combine_peaks/GRCm39-macs2.log

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job combine_peaks since they might be corrupted:
/scratch/dzijlmans/DZ034/results/macs2/GRCm39_combinedsummits.bed

```

**To Reproduce**
**config.yaml**
```
# tab-separated file of the samples
samples: samples.tsv

# pipeline file locations
result_dir: ./results  # where to store results
genome_dir: ./genomes  # where to look for or download the genomes
fastq_dir: ./fastq  # where to look for or download the fastqs


# contact info for multiqc report and trackhub
email: d.zijlmans@science.ru.nl

# produce a UCSC trackhub?
create_trackhub: True

# how to handle replicates
biological_replicates: fisher  # change to "keep" to not combine them
technical_replicates: merge    # change to "keep" to not combine them

# which trimmer to use
trimmer: fastp

# which aligner to use
aligner: bwa-mem

# filtering after alignment
remove_blacklist: True
min_mapping_quality: 30
only_primary_align: True

# peak caller
peak_caller:
  macs2:
      --keep-dup 1 --buffer-size 10000
```

**samples.tsv**
```
# for help with filling out the samples.tsv:
# https://vanheeringen-lab.github.io/seq2science/content/workflows/chip_seq.html#filling-out-the-samples-tsv
# also make sure that you use tab as a delimiter
sample	assembly	descriptive_name
DZ-EmT-cl2-H2K27me3-1-Z16_S8	GRCm39	EmT-cl2-k27me3-1
DZ-EmT-cl2-H2K27me3-2-Z17_S16	GRCm39	EmT-cl2-k27me3-2
DZ-EmT-cl2-HA-1-Z14_S6	GRCm39	EmT-cl2-ha-1
DZ-EmT-cl2-HA-2-Z15_S7	GRCm39	EmT-cl2-ha-2
DZ-EmT-cl2-input-Z18_S11	GRCm39	EmT-cl2-input
DZ-R1WT-Ezh2-1-Z01_S1	GRCm39	R1WT-ezh2-1
DZ-R1WT-Ezh2-2-Z03_S2	GRCm39	R1WT-ezh2-2
DZ-R1WT-H2K27me3-2-Z05_S12	GRCm39	R1WT-k27me3-2
DZ-R1WT-HA-1-Z06_S3	GRCm39	R1WT-ha-1
DZ-R1WT-HA-2-Z07_S13	GRCm39	R1WT-ha-2
DZ-R1WT-Input-Z13_S10	GRCm39	R1WT-input
DZ-R1WT-Sall1-1-Z08_S4	GRCm39	R1WT-sall1-1
DZ-R1WT-Sall1-2-Z09_S14	GRCm39	R1WT-sall1-2
DZ-R1WT-Sall4-1-Z11_S15	GRCm39	R1WT-sall4-1
DZ-R1WT-Sall4-2-Z12_S5	GRCm39	R1WT-sall4-2
```

**log file**
```
2021-01-13 22:29:58,526 - INFO - No config found.
2021-01-13 22:29:58,526 - INFO - Creating new config.
2021-01-13 22:29:58,534 - INFO - Using included version of MDmodule.
2021-01-13 22:30:03,338 - INFO - Using system version of MEME.
2021-01-13 22:30:10,529 - INFO - Using system version of MEMEW.
2021-01-13 22:30:19,496 - INFO - Using system version of DREME.
2021-01-13 22:30:23,925 - INFO - Using system version of Weeder.
2021-01-13 22:30:27,552 - INFO - Using system version of GADEM.
2021-01-13 22:30:27,553 - INFO - Using included version of MotifSampler.
2021-01-13 22:30:31,208 - INFO - Using system version of Trawler.
2021-01-13 22:30:31,209 - INFO - Using included version of Improbizer.
2021-01-13 22:30:31,209 - INFO - Using included version of BioProspector.
2021-01-13 22:30:31,209 - INFO - Using included version of Posmo.
2021-01-13 22:30:31,210 - INFO - Using included version of ChIPMunk.
2021-01-13 22:30:31,210 - INFO - Using included version of AMD.
2021-01-13 22:30:31,210 - INFO - Using included version of HMS.
2021-01-13 22:30:34,906 - INFO - Using system version of Homer.
2021-01-13 22:30:38,629 - INFO - Using system version of XXmotif.
2021-01-13 22:30:42,224 - INFO - Using system version of ProSampler.
2021-01-13 22:30:42,224 - WARNING - Yamda not in config
2021-01-13 22:30:45,815 - INFO - Using system version of DiNAMO.
2021-01-13 22:30:53,364 - WARNING - RPMCMC not found. To include it you will have to install it.
2021-01-13 22:30:53,378 - INFO - Configuration file: /home/dzijlmans/.config/gimmemotifs/gimmemotifs.cfg
Traceback (most recent call last):
  File "/vol/mbconda/dzijlmans/envs/seq2science/lib/python3.8/site-packages/seq2science/.snakemake/eb131cbd/bin/combine_peaks", line 9, in <module>
    from gimmemotifs import __version__
  File "/vol/mbconda/dzijlmans/envs/seq2science/lib/python3.8/site-packages/seq2science/.snakemake/eb131cbd/lib/python3.8/site-packages/gimmemotifs/__init__.py", line 61, in <module>
    from . import denovo      # noqa: F401
  File "/vol/mbconda/dzijlmans/envs/seq2science/lib/python3.8/site-packages/seq2science/.snakemake/eb131cbd/lib/python3.8/site-packages/gimmemotifs/denovo.py", line 52, in <module>
    from gimmemotifs.report import create_denovo_motif_report
  File "/vol/mbconda/dzijlmans/envs/seq2science/lib/python3.8/site-packages/seq2science/.snakemake/eb131cbd/lib/python3.8/site-packages/gimmemotifs/report.py", line 19, in <module>
    from pandas.core.indexing import _non_reducing_slice
ImportError: cannot import name '_non_reducing_slice' from 'pandas.core.indexing' (/vol/mbconda/dzijlmans/envs/seq2science/lib/python3.8/site-packages/seq2science/.snakemake/eb131cbd/lib/python3.8/site-packages/pandas/core/indexing.py)
```

**Expected behavior**

**Screenshots**

**Comment by Maarten-vd-Sande** [comment]
Thanks for the report! I will see if I can fix it somewhere this week.

**Comment by Maarten-vd-Sande** [comment]
This should now be fixed. Update to version 0.4.2 and continue where you left off.

conda activate seq2science
conda install seq2science=0.4.2
seq2science run ...
