### ISSUE TITLE
BUG: Pytxi cannot checkout branch

### ISSUE THREAD

**Issue by tilschaef** [vanheeringen-lab/seq2science#851]
**Describe the bug**
Seems pytxi tries to checkout a tagged commit during installation.  Is that part still necessary?
```
failed
Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/vanheeringen-lab/pytxi.git /scratch/jroubroeks/tmp/I3tJ/pip-req-build-wr4pc4tu
  WARNING: Did not find branch or tag '3522d3f', assuming revision or ref.
  Running command git checkout -q 3522d3f
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [83 lines of output]
      /scratch/jroubroeks/tmp/I3tJ/pip-build-env-lefp3hi_/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'authors'
        warnings.warn(msg)
      /scratch/jroubroeks/tmp/I3tJ/pip-build-env-lefp3hi_/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:102: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
        warnings.warn(msg, _ExperimentalProjectMetadata)
      configuration error: `project.license` must be valid exactly by one definition (2 matches found):
      
          - keys:
              'file': {type: string}
            required: ['file']
          - keys:
              'text': {type: string}
            required: ['text']
      
      DESCRIPTION:
          `Project license <https://www.python.org/dev/peps/pep-0621/#license>`_.
      
      GIVEN VALUE:
          "MIT"
      
      OFFENDING RULE: 'oneOf'
      
      DEFINITION:
          {
              "oneOf": [
                  {
                      "properties": {
                          "file": {
                              "type": "string",
                              "$$description": [
                                  "Relative path to the file (UTF-8) which contains the license for the",
                                  "project."
                              ]
                          }
                      },
                      "required": [
                          "file"
                      ]
                  },
                  {
                      "properties": {
                          "text": {
                              "type": "string",
                              "$$description": [
                                  "The license of the project whose meaning is that of the",
                                  "`License field from the core metadata",
                                  "<https://packaging.python.org/specifications/core-metadata/#license>`_."
                              ]
                          }
                      },
                      "required": [
                          "text"
                      ]
                  }
              ]
          }
      Traceback (most recent call last):
        File "/vol/mbconda/jroubroeks/anaconda3/envs/S2S/lib/python3.8/site-packages/seq2science/.snakemake/4c7e32e0/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/vol/mbconda/jroubroeks/anaconda3/envs/S2S/lib/python3.8/site-packages/seq2science/.snakemake/4c7e32e0/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/vol/mbconda/jroubroeks/anaconda3/envs/S2S/lib/python3.8/site-packages/seq2science/.snakemake/4c7e32e0/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/scratch/jroubroeks/tmp/I3tJ/pip-build-env-lefp3hi_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/scratch/jroubroeks/tmp/I3tJ/pip-build-env-lefp3hi_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/scratch/jroubroeks/tmp/I3tJ/pip-build-env-lefp3hi_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 25, in <module>
          setup(**project)
        File "/scratch/jroubroeks/tmp/I3tJ/pip-build-env-lefp3hi_/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/scratch/jroubroeks/tmp/I3tJ/pip-build-env-lefp3hi_/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 122, in setup
          dist.parse_config_files()
        File "/scratch/jroubroeks/tmp/I3tJ/pip-build-env-lefp3hi_/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 854, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/scratch/jroubroeks/tmp/I3tJ/pip-build-env-lefp3hi_/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 54, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "/scratch/jroubroeks/tmp/I3tJ/pip-build-env-lefp3hi_/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 120, in read_configuration
          validate(subset, filepath)
        File "/scratch/jroubroeks/tmp/I3tJ/pip-build-env-lefp3hi_/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 43, in validate
          raise error from None
      ValueError: invalid pyproject.toml config: `project.license`
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


CondaEnvException: Pip failed

d libprotobuf                          (00m:00s)               3 MB      3 MB/s
Finished pip                                  (00m:00s)               2 MB      2 MB/s
Finished ucsc-genepredtobed                   (00m:00s)             131 KB    142 KB/s
Finished python                               (00m:00s)              27 MB     29 MB/s
Finished genomepy                             (00m:00s)              66 KB     67 KB/s
Finished setuptools                           (00m:00s)               1 MB      1 MB/s
Finished pysocks                              (00m:00s)              28 KB     28 KB/s
Finished brotlipy                             (00m:00s)             342 KB    343 KB/s
Finished biopython                            (00m:00s)               3 MB      3 MB/s
Finished charset-normalizer                   (00m:00s)              35 KB     33 KB/s

  File "/vol/mbconda/jroubroeks/anaconda3/envs/S2S/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 333, in create
```

**Comment by Maarten-vd-Sande** [comment]
Not sure if this is related to the pytxi thingy. Could be related to an invalid toml in pytxi?

https://github.com/vanheeringen-lab/pytxi/blob/master/pyproject.toml

Idk, the toml problem has been popping up on different places.. Maybe we should pin the toml version or sth? Maybe its not toml but setuptools? No clue...

**Comment by Maarten-vd-Sande** [comment]
Our pyproject.toml seems to use v59.4.0 for building seq2science. Maybe we should specify that version for the requirements?

https://github.com/vanheeringen-lab/seq2science/blob/master/pyproject.toml#L29

**Comment by tilschaef** [comment]
I haven't tested that one yet but I just tried to manually create a pytxi environment and encountered the same error.  I am afraid that, even if we fix it in seq2science, the error could still persist in down-stream packages

**Comment by siebrenf** [comment]
I'll look into this. 

Need to learn how to update the pytxi toml properly... If only the setuptools + toml docs were complete 😭
