### ISSUE TITLE
BUG: Problem with the Initiation

### ISSUE THREAD

**Issue by XimenezJP** [vanheeringen-lab/seq2science#942]
**Describe the bug**
I have tried to initiate the rna-seq analysis but I am getting the following error message:

Traceback (most recent call last):
  File "/data1/home/joao/miniconda3/envs/seq2science/bin/seq2science", line 6, in <module>
    from seq2science.cli import seq2science_main
  File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/seq2science/__init__.py", line 1, in <module>
    from . import util
  File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/seq2science/util.py", line 21, in <module>
    import genomepy
  File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/genomepy/__init__.py", line 10, in <module>
    from genomepy.annotation import Annotation, query_mygene
  File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/genomepy/annotation/__init__.py", line 11, in <module>
    from genomepy.annotation.mygene import _map_genes, query_mygene
  File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/genomepy/annotation/mygene.py", line 10, in <module>
    from genomepy.caching import cache_exp_short, disk_cache
  File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/genomepy/caching.py", line 19, in <module>
    disk_cache = Cache(directory=genomepy_cache_dir)
  File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/diskcache/core.py", line 2433, in reset
    ((old_value,),) = sql(
sqlite3.OperationalError: database is locked

I also tried seq2science clean and got the same error message!

**Comment by Maarten-vd-Sande** [comment]
Its a cache error from a downstream package. I think you have to manually remove the cache to resolve this, from memory:

‘rm -r ~/.cache/genomepy’

Let me know if that solves it, I’m out on holidays. I’ll come back to it in the new year if it doesn’t solve your issue.

Happy holidays ☃️

**Comment by XimenezJP** [comment]
Hi Maarten,

It fixed the problem for the initiation but now I am having a different problem when I try to run the rna-seq:

Traceback (most recent call last):
  File "/data1/home/joao/miniconda3/envs/seq2science/bin/seq2science", line 6, in <module>
    from seq2science.cli import seq2science_main
  File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/seq2science/__init__.py", line 1, in <module>
    from . import util
  File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/seq2science/util.py", line 21, in <module>
    import genomepy
  File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/genomepy/__init__.py", line 10, in <module>
    from genomepy.annotation import Annotation, query_mygene
  File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/genomepy/annotation/__init__.py", line 11, in <module>
    from genomepy.annotation.mygene import _map_genes, query_mygene
  File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/genomepy/annotation/mygene.py", line 10, in <module>
    from genomepy.caching import cache_exp_short, disk_cache
  File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/genomepy/caching.py", line 19, in <module>
    disk_cache = Cache(directory=genomepy_cache_dir)
  File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/diskcache/core.py", line 2440, in reset
    sql('PRAGMA %s = %s' % (pragma, value)).fetchall()
sqlite3.OperationalError: disk I/O error

Thank you for your help!

Happy holidays!

**Comment by Maarten-vd-Sande** [comment]
I’ll come back to this in the new year! Somewhere hopefully in the first week.

On 25 Dec 2022, at 21:46, João Paulo Ximenez ***@***.***> wrote:

﻿

Hi Maarten,

It fixed the problem for the initiation but now I am having a different problem when I try to run the rna-seq:

Traceback (most recent call last):
File "/data1/home/joao/miniconda3/envs/seq2science/bin/seq2science", line 6, in
from seq2science.cli import seq2science_main
File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/seq2science/init.py", line 1, in
from . import util
File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/seq2science/util.py", line 21, in
import genomepy
File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/genomepy/init.py", line 10, in
from genomepy.annotation import Annotation, query_mygene
File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/genomepy/annotation/init.py", line 11, in
from genomepy.annotation.mygene import _map_genes, query_mygene
File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/genomepy/annotation/mygene.py", line 10, in
from genomepy.caching import cache_exp_short, disk_cache
File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/genomepy/caching.py", line 19, in
disk_cache = Cache(directory=genomepy_cache_dir)
File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/diskcache/core.py", line 478, in init
self.reset(key, value, update=False)
File "/data1/home/joao/miniconda3/envs/seq2science/lib/python3.8/site-packages/diskcache/core.py", line 2440, in reset
sql('PRAGMA %s = %s' % (pragma, value)).fetchall()
sqlite3.OperationalError: disk I/O error

Thank you for your help!

Happy holidays!

**Comment by Maarten-vd-Sande** [comment]
I'm not sure about that error! What happens if you delete the cache again? Does it still persist?

Or are you running seq2science in a folder that is being synced by e.g. google drive or dropbox? This might be related: https://stackoverflow.com/a/48479810/9544516

**Comment by XimenezJP** [comment]
Hi Maarten,

Thank you for your help! 

Apparently after `rm -r ~/.cache/genomepy`

It is working perfectly again!

Best

Joao

**Comment by Maarten-vd-Sande** [comment]
Awesome your problem is resolved now :smile:
